### ISSUE TITLE
Remake button mixin

### ISSUE THREAD

**Issue by Jursdotme** [Jursdotme/secondthought#16]
Start here:

```scss
// buttons.scss
$button-colors: (
  error: (#d82d2d, #666),
  success: (#52bf4a, #fff),
  warning: (#c23435, #fff),
  default: (#fafafa, #999)
);

$button-sizes: (
  default: (5px 10px, 1rem),
  extra-small: (5px 10px, 1rem),
  small: (5px 10px, 1rem),
  medium: (5px 10px, 1rem),
  large: (5px 10px, 1rem),
  huge: (5px 10px, 1rem)
);
 
.btn {
  display: inline-block;
  padding: .5em;
  background: #ccc;
  color: #666;
  
  @each $name, $sizes in $button-sizes {
    $padding: nth($sizes, 1);
    $font-size: nth($sizes, 2);
     
    &-#{$name} {
      padding: $padding;
      font-size: $font-size;
    }  
  }
   
  @each $name, $colors in $button-colors {
    $bgcolor: nth($colors, 1);
    $fontcolor: nth($colors, 2);
     
    &-#{$name} {
      background-color: $bgcolor;
      color: $fontcolor;
    }  
  }
}
```
